### ISSUE TITLE
Get rid of rimraf

### ISSUE THREAD

**Issue by vweevers** [Level/memdown#114]
This was added in https://github.com/Level/memdown/commit/001c86e3140dda6faa9e76cfc6013682e39479d7, excluded from browser builds in https://github.com/Level/memdown/commit/80822a7889cc31a38bc9c239b3ea1bc0bc04864d and necessary because [`abstract-leveldown/testCommon.js`](
https://github.com/Level/abstract-leveldown/blob/89a1f487e5607fc1239b14d229b2c8f26460afba/testCommon.js#L3) requires `rimraf`.

I think we should solve this in `abstract-leveldown` so that memdown (and others) don't need these hacks. I'll open an issue. /cc @ralphtheninja

**Comment by vweevers** [comment]
Actually I'll first test if the hacks are still required.

**Comment by vweevers** [comment]
They aren't :) Looks like browserify is smart enough to respect the `browser` configuration of `abstract-leveldown`, and replace `rimraf` with an empty module.

**Comment by ralphtheninja** [comment]
@vweevers So we can just remove the `rimraf` dependency now?

**Comment by vweevers** [comment]
No, because of https://github.com/Level/memdown/pull/116#issuecomment-355759109

**Comment by vweevers** [comment]
Done in #174
