### ISSUE TITLE
Rename changelog to upgrade guide?

### ISSUE THREAD

**Issue by vweevers** [Level/memdown#119]
What we have here is more like the upgrade guide of `abstract-leveldown`. WDYT @ralphtheninja?

**Comment by ralphtheninja** [comment]
Hmm where is the changelog?

**Comment by vweevers** [comment]
https://github.com/Level/memdown/blob/v2/CHANGELOG.md

**Comment by ralphtheninja** [comment]
Oh, sorry, was looking at the master branch on my phone. Sure, lets rename it.
