### ISSUE TITLE
Was the .destroy method removed?

### ISSUE THREAD

**Issue by roccomuso** [Level/memdown#146]

**Comment by vweevers** [comment]
Yes, because memdown v2 no longer has global state. There's no point to `destroy` :)

**Comment by roccomuso** [comment]
hm ok, Actually I'm trying to have a sort of fallback from the persistent leveldown to memdown and the `destroy` method is required in order to have compliant API and passing the tests.

Any hint or workaround?

**Comment by ralphtheninja** [comment]
@roccomuso Check if method exists before calling it
