### ISSUE TITLE
Remove --stderr argument from test script

### ISSUE THREAD

**Issue by vweevers** [Level/memdown#155]
First find out why it was added. Doesn't seem like we need it.

**Comment by vweevers** [comment]
It was introduced here: https://github.com/Level/memdown/commit/aaaa326a261b6e05cfce3979bbd322d5bbd2d1bd#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R23

But I can't find usage of `stderr` in any revision of `test.js`, `memdown.js`, `abstract-leveldown/abstract/batch-test` or `abstract/chained-batch-test.js`. 

I could search more files but 99% sure we can just remove it.

**Comment by ralphtheninja** [comment]
@vweevers Maybe it was related to the `tap` module? (we didn't use `tape` at the time)

**Comment by vweevers** [comment]
Could be! https://github.com/tapjs/node-tap/commit/bdc03c60c756fcddff7ea7b1661c7d108cf6b036

In any case, I didn't find usage in current `node_modules`, so safe to remove now.
