### ISSUE TITLE
Unlike other engines, memdown stores passed Buffers by reference

### ISSUE THREAD

**Issue by abacabadabacaba** [Level/memdown#207]
Most `abstract-leveldown` stores store the data by value. Thus, when a method such as `put` is called with a Buffer, they record a byte sequence that it represents and store that.

Unlike other stores, `memdown` stores JavaScript values as is. The problems with that is that Buffer values are mutable: their underlying memory, and thus the byte sequence that they represent, may legitimately change. In general, such changes are not expected to have a side effect of changing the contents of an `abstract-memdown` store, but this is what happens with `memdown`, because it doesn't copy the Buffer values.

Not only it makes testing more difficult (`memdown` cannot be used as a drop-in replacement of another store for testing), it can also result in inconsistent behavior if the ordering of keys is violated.

I think that `memdown`'s behavior should be changed to copy Buffer values, to match the behavior of other stores. A constructor options may be provided to turn off the copying as an optimization (which will require, however, that any code using `memdown` does not modify the underlying memory of any passed or returned Buffer).

**Comment by vweevers** [comment]
Personally I find it acceptable, and even expected, that values in an in-memory store are mutable. That does however assume a common usage pattern, where after storing values you are done with them. I believe this is why no one has raised this issue until now. To keep performance as-is, I prefer to keep the current behavior and make copying opt-in.

I'm not sure where to solve this. We could do the copying here:

https://github.com/Level/memdown/blob/0f9b2e6c38d07285523cf6c00c7038702b96f2bb/memdown.js#L178-L184

Along the lines of:

```js
MemDOWN.prototype._serializeKey = function (key) {
  if (Buffer.isBuffer(key)) {
    return this._copy ? Buffer.from(key) : key
  }

  return Buffer.from(String(key))
}
```

However, `_serializeKey` is also used on range options like `gt`, which shouldn't be copied. So we'd have do it per method, i.e. in `put()` and `batch()`. But there we don't know whether the input came from a buffer or a string; if it was the latter we would again create unnecessary copies (effectively: `Buffer.from(Buffer.from(String(key)))`.

**Comment by abacabadabacaba** [comment]
At least, the current behavior should be documented. Also, modifying Buffer's memory breaks snapshot guarantee, because snapshots also don't copy anything.

**Comment by vweevers** [comment]
Would you like to send a PR to document the current behavior?

**Comment by vweevers** [comment]
I documented it in https://github.com/Level/memory-level. Closing for now, until other folks share the same concern.
