### ISSUE TITLE
Add new publisher(s)

### ISSUE THREAD

**Issue by rvagg** [Level/memdown#27]
I feel like there are others who have much more vested interest in the success and stability of this lib than I do at the moment. For me it hasn't graduated beyond being an interesting exercise in extending the leveldown pattern and as a useful backend for tests. I'd like to `npm owner add` at least one person to it. I'd prefer not to open that right up to everyone on the collaborators list as I believe that even OPEN Open Source needs a tight release mechanism.

I'd like to hear thoughts from others, particularly those who are using this in some _real_ way. I'm nominating @nolanlawson.

**Comment by nolanlawson** [comment]
seems done now; there are plenty of npm owners
