### ISSUE TITLE
Fails against abstract-leveldown 2.5.0, works in 2.4.1

### ISSUE THREAD

**Issue by nolanlawson** [Level/memdown#55]
See https://github.com/Level/memdown/issues/50

**Comment by nolanlawson** [comment]
See https://github.com/Level/abstract-leveldown/pull/96#issuecomment-246122818

**Comment by juliangruber** [comment]
2.6.1 works!

**Comment by nolanlawson** [comment]
Closing in that case. Thank you! :)
