### ISSUE TITLE
Breaking change in 1.2.3

### ISSUE THREAD

**Issue by kumavis** [Level/memdown#64]
I haven't investigated it yet but here is the automated issue:
https://github.com/ethereumjs/ethereumjs-vm/pull/111

**Comment by vweevers** [comment]
Looking at the CI logs, it's a duplicate of #62, which was fixed in 1.2.4.

If upgrading to 1.2.4 doesn't help, please feel free to re-open.

**Comment by kumavis** [comment]
👍 thanks 👍
