### ISSUE TITLE
clean up null/undefined check in _put

### ISSUE THREAD

**Issue by ralphtheninja** [Level/memdown#71]
https://github.com/Level/memdown/blob/0454e57399616b81fd76acc4f69fe17859be1fe9/memdown.js#L148

Prerequisite: https://github.com/Level/abstract-leveldown/pull/119 has to be released

**Comment by vweevers** [comment]
@ralphtheninja by clean up you mean remove this line?

**Comment by ralphtheninja** [comment]
> @ralphtheninja by clean up you mean remove this line?

Aye, but only once `abstract-leveldown` takes care of it, which iirc is not the case now. Also see https://github.com/Level/abstract-leveldown/issues/120

**Comment by vweevers** [comment]
Actually, `abstract-leveldown` also does this in [`_serializeValue`](https://github.com/Level/abstract-leveldown/blob/24e11812d3e247bc2e6cb67955dd06614488333e/abstract-leveldown.js#L257), so (at least to maintain current behavior) it's safe to remove this line.

**Comment by vweevers** [comment]
Removed in #106.
