### ISSUE TITLE
zuul problems

### ISSUE THREAD

**Issue by ralphtheninja** [Level/memdown#72]
Sometimes the tests fail with the following error:

```
# test iterator with end being a midway key (50.5)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connection refused: localtunnel.me:40685 (check your firewall settings)
    at Socket.<anonymous> (/home/travis/build/Level/memdown/node_modules/localtunnel/client.js:84:32)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

This is super annoying.

**Comment by ralphtheninja** [comment]
Possibly related https://github.com/defunctzombie/zuul/issues/251

**Comment by ralphtheninja** [comment]
Also, the log is always too long on travis so you can't see the error if it happens far down.

**Comment by ralphtheninja** [comment]
Do we really need to test on _all_ these targets? Seems a bit overkill to me.

```
$ cat .zuul.yml 
ui: tape
browsers:
  - name: chrome
    version: 50..latest
  - name: firefox
    version: 45..latest
  - name: safari
    version: [8, 9..latest]
  - name: ie
    version: 10..latest
  - name: microsoftedge
    version: 13..latest
  - name: iphone
    version: [7.1, 8.4, 9.1..latest]
  - name: ipad
    version: [7.1, 8.4, 9.1..latest]
  - name: android
    version: 4.4..latest
```

**Comment by ralphtheninja** [comment]
Reducing the amount of browsers to test on might help out with this problem, see https://github.com/SpainTrain/querystring-es3/commit/ca0a9f667f56a8d01913175ae8e42a9059fa63b6

**Comment by vweevers** [comment]
@ralphtheninja maybe look at `readable-stream` for inspiration, looks like [it uses separate travis builds per browser](https://github.com/nodejs/readable-stream/blob/master/.travis.yml) which might help with the tunnel issue (that's a guess).

**Comment by ralphtheninja** [comment]
Sides quests everywhere ;) I think I'm on side quest, depth four at the moment :grinning:

**Comment by ralphtheninja** [comment]
https://github.com/Level/memdown/pull/69/commits/f0b4b76a1a9ca4a158a99a2c13e18e0b70b4d19f
