### ISSUE TITLE
Disable coveralls comments on PRs?

### ISSUE THREAD

**Issue by vweevers** [Level/memdown#83]
Is it possible to disable these noisy coveralls comments?

![image](https://user-images.githubusercontent.com/3055345/31053318-357e58be-a69b-11e7-8a2c-e7a7c3318f05.png)

The status check is enough I think.

**Comment by ralphtheninja** [comment]
I think it should be enough to remove `istanbul-coveralls` from

```json
"report-coverage": "npm run coverage && istanbul-coveralls"
```

**Comment by ralphtheninja** [comment]
Oh wait, then we won't get any reports back at all, nevermind.

**Comment by vweevers** [comment]
Cool, we can just login with GitHub. There's an option:

![image](https://user-images.githubusercontent.com/3055345/31054293-ff7f2224-a6af-11e7-9802-487b01cb2f46.png)
