### ISSUE TITLE
Remove global store and location option?

### ISSUE THREAD

**Issue by vweevers** [Level/memdown#84]
This feature doesn't fit Node.js patterns and even in browsers nowadays, global state is a no-no. Better put, leaking into global state. There are times when it is appropriate (e.g. React with a global store) but IMO this is an application-level choice, not to be made by a module.

Without a global store, the "location" parameter becomes irrelevant. Usage then is just `memdown()`. If you do need global state, you can attach the database to a global yourself, e.g. `window.db = db`.

WDYT @ralphtheninja @juliangruber? We can do this after releasing `levelup@2`.

**Comment by juliangruber** [comment]
+10000 for removing the global state, this has weirded me out a lot too

**Comment by ralphtheninja** [comment]
Go for it. I hate global state :laughing:

**Comment by ralphtheninja** [comment]
I want to remove the `Testing` section in the README as well.

**Comment by vweevers** [comment]
> I want to remove the Testing section in the README as well.

What's the harm? We have 6 npm scripts here so I think this section is a nice guide for new contributors.

**Comment by vweevers** [comment]
Ah, I missed your edit. Hold on, lemme open a new issue for this.

**Comment by ralphtheninja** [comment]
Yeah, I changed my mind. I realized removing completely was way too harsh.

**Comment by vweevers** [comment]
Removing `location` depends on Level/abstract-leveldown#63. I think to start, we can move the `location !== undefined` check from `abstract-leveldown` to `leveldown` and others. So we don't yet change the API (like Level/abstract-leveldown#65), we merely relax it.

Alternatively, if there are too many backends to be updated, we can have `memdown` pass a dummy location to `abstract-leveldown`.

**Comment by vweevers** [comment]
Done in v2 branch.
