### ISSUE TITLE
Remove testing section from readme?

### ISSUE THREAD

**Issue by vweevers** [Level/memdown#86]
Continuing from https://github.com/Level/memdown/issues/84#issuecomment-333413290. @ralphtheninja please elaborate :)

**Comment by ralphtheninja** [comment]
I want to reduce some of the information, mentioning `npm test` in a node.js README is being overly detailed, it's convention. The linter could be replaced by `standard` and also be part of the test. Maybe just mention how you can test locally in your browser and run coverage.

**Comment by vweevers** [comment]
> I want to reduce some of the information, mentioning npm test in a node.js README is being overly detailed, it's convention.

Agreed 👍 

> The linter could be replaced by standard

#87.

> and also be part of the test.

The current linter is indeed part of `npm test` so we can remove these instructions 👍
