### ISSUE TITLE
Tweak readme

### ISSUE THREAD

**Issue by vweevers** [Level/memdown#95]
- [x] add node version badge
- [x] remove greenkeeper badge
- [x] use SVG badge for Travis
- [x] add level badge
- [x] normalize markdown headers (`##` instead of `--`)
- [x] common spelling: `Licence` => `License`
- [x] `database` => `store`

**Comment by vweevers** [comment]
We didn't explicitly drop 0.12 yet. Can do that as part of v2.

**Comment by vweevers** [comment]
Not sure why I marked `add node version badge` and `add SVG badge for Travis` as done, they aren't.

**Comment by vweevers** [comment]
My bad @ralphtheninja, I see now that you are working on this in the `readme` branch.

**Comment by ralphtheninja** [comment]
No worries. I wanted to mention it here but forgot.
