### ISSUE TITLE
Update readme example

### ISSUE THREAD

**Issue by vweevers** [Level/memdown#98]

**Comment by kumavis** [comment]
seems like its like this now?

```js
  const db = new levelup(new memdown())
```

**Comment by ralphtheninja** [comment]
@kumavis Correct.

**Comment by kumavis** [comment]
https://github.com/Level/memdown/pull/100

**Comment by vweevers** [comment]
Further tweaks:

- [ ] `new memdown()` =>  `memdown()`
- [ ] `db.createReadStream({ keyAsBuffer: false, valueAsBuffer: false })`
- [ ] Remove: "`levelup` allows you to pass a `db` option .."
